// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterFrontend.proto

#include "masterFrontend.pb.h"
#include "masterFrontend.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace masterFrontend {

static const char* getKVipport_method_names[] = {
  "/masterFrontend.getKVipport/receive_request",
};

std::unique_ptr< getKVipport::Stub> getKVipport::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< getKVipport::Stub> stub(new getKVipport::Stub(channel));
  return stub;
}

getKVipport::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_receive_request_(getKVipport_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status getKVipport::Stub::receive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::masterFrontend::masterReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_receive_request_, context, request, response);
}

void getKVipport::Stub::experimental_async::receive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_receive_request_, context, request, response, std::move(f));
}

void getKVipport::Stub::experimental_async::receive_request(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::masterFrontend::masterReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_receive_request_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::masterFrontend::masterReply>* getKVipport::Stub::Asyncreceive_requestRaw(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::masterFrontend::masterReply>::Create(channel_.get(), cq, rpcmethod_receive_request_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::masterFrontend::masterReply>* getKVipport::Stub::PrepareAsyncreceive_requestRaw(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::masterFrontend::masterReply>::Create(channel_.get(), cq, rpcmethod_receive_request_, context, request, false);
}

getKVipport::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      getKVipport_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< getKVipport::Service, ::masterFrontend::frontendRequest, ::masterFrontend::masterReply>(
          std::mem_fn(&getKVipport::Service::receive_request), this)));
}

getKVipport::Service::~Service() {
}

::grpc::Status getKVipport::Service::receive_request(::grpc::ServerContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace masterFrontend

