// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: masterFrontend.proto

#ifndef PROTOBUF_INCLUDED_masterFrontend_2eproto
#define PROTOBUF_INCLUDED_masterFrontend_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_masterFrontend_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_masterFrontend_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_masterFrontend_2eproto();
namespace masterFrontend {
class getServerListReply;
class getServerListReplyDefaultTypeInternal;
extern getServerListReplyDefaultTypeInternal _getServerListReply_default_instance_;
class getServerListRequest;
class getServerListRequestDefaultTypeInternal;
extern getServerListRequestDefaultTypeInternal _getServerListRequest_default_instance_;
}  // namespace masterFrontend
namespace google {
namespace protobuf {
template<> ::masterFrontend::getServerListReply* Arena::CreateMaybeMessage<::masterFrontend::getServerListReply>(Arena*);
template<> ::masterFrontend::getServerListRequest* Arena::CreateMaybeMessage<::masterFrontend::getServerListRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace masterFrontend {

// ===================================================================

class getServerListRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:masterFrontend.getServerListRequest) */ {
 public:
  getServerListRequest();
  virtual ~getServerListRequest();

  getServerListRequest(const getServerListRequest& from);

  inline getServerListRequest& operator=(const getServerListRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  getServerListRequest(getServerListRequest&& from) noexcept
    : getServerListRequest() {
    *this = ::std::move(from);
  }

  inline getServerListRequest& operator=(getServerListRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const getServerListRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const getServerListRequest* internal_default_instance() {
    return reinterpret_cast<const getServerListRequest*>(
               &_getServerListRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(getServerListRequest* other);
  friend void swap(getServerListRequest& a, getServerListRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline getServerListRequest* New() const final {
    return CreateMaybeMessage<getServerListRequest>(nullptr);
  }

  getServerListRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<getServerListRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const getServerListRequest& from);
  void MergeFrom(const getServerListRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(getServerListRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string user_name = 1;
  void clear_user_name();
  static const int kUserNameFieldNumber = 1;
  const ::std::string& user_name() const;
  void set_user_name(const ::std::string& value);
  #if LANG_CXX11
  void set_user_name(::std::string&& value);
  #endif
  void set_user_name(const char* value);
  void set_user_name(const char* value, size_t size);
  ::std::string* mutable_user_name();
  ::std::string* release_user_name();
  void set_allocated_user_name(::std::string* user_name);

  // @@protoc_insertion_point(class_scope:masterFrontend.getServerListRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_masterFrontend_2eproto;
};
// -------------------------------------------------------------------

class getServerListReply final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:masterFrontend.getServerListReply) */ {
 public:
  getServerListReply();
  virtual ~getServerListReply();

  getServerListReply(const getServerListReply& from);

  inline getServerListReply& operator=(const getServerListReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  getServerListReply(getServerListReply&& from) noexcept
    : getServerListReply() {
    *this = ::std::move(from);
  }

  inline getServerListReply& operator=(getServerListReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const getServerListReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const getServerListReply* internal_default_instance() {
    return reinterpret_cast<const getServerListReply*>(
               &_getServerListReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(getServerListReply* other);
  friend void swap(getServerListReply& a, getServerListReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline getServerListReply* New() const final {
    return CreateMaybeMessage<getServerListReply>(nullptr);
  }

  getServerListReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<getServerListReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const getServerListReply& from);
  void MergeFrom(const getServerListReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(getServerListReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string server_ipport = 1;
  int server_ipport_size() const;
  void clear_server_ipport();
  static const int kServerIpportFieldNumber = 1;
  const ::std::string& server_ipport(int index) const;
  ::std::string* mutable_server_ipport(int index);
  void set_server_ipport(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_server_ipport(int index, ::std::string&& value);
  #endif
  void set_server_ipport(int index, const char* value);
  void set_server_ipport(int index, const char* value, size_t size);
  ::std::string* add_server_ipport();
  void add_server_ipport(const ::std::string& value);
  #if LANG_CXX11
  void add_server_ipport(::std::string&& value);
  #endif
  void add_server_ipport(const char* value);
  void add_server_ipport(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& server_ipport() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_server_ipport();

  // @@protoc_insertion_point(class_scope:masterFrontend.getServerListReply)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField<::std::string> server_ipport_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_masterFrontend_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// getServerListRequest

// string user_name = 1;
inline void getServerListRequest::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& getServerListRequest::user_name() const {
  // @@protoc_insertion_point(field_get:masterFrontend.getServerListRequest.user_name)
  return user_name_.GetNoArena();
}
inline void getServerListRequest::set_user_name(const ::std::string& value) {
  
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:masterFrontend.getServerListRequest.user_name)
}
#if LANG_CXX11
inline void getServerListRequest::set_user_name(::std::string&& value) {
  
  user_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:masterFrontend.getServerListRequest.user_name)
}
#endif
inline void getServerListRequest::set_user_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:masterFrontend.getServerListRequest.user_name)
}
inline void getServerListRequest::set_user_name(const char* value, size_t size) {
  
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:masterFrontend.getServerListRequest.user_name)
}
inline ::std::string* getServerListRequest::mutable_user_name() {
  
  // @@protoc_insertion_point(field_mutable:masterFrontend.getServerListRequest.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* getServerListRequest::release_user_name() {
  // @@protoc_insertion_point(field_release:masterFrontend.getServerListRequest.user_name)
  
  return user_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void getServerListRequest::set_allocated_user_name(::std::string* user_name) {
  if (user_name != nullptr) {
    
  } else {
    
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:masterFrontend.getServerListRequest.user_name)
}

// -------------------------------------------------------------------

// getServerListReply

// repeated string server_ipport = 1;
inline int getServerListReply::server_ipport_size() const {
  return server_ipport_.size();
}
inline void getServerListReply::clear_server_ipport() {
  server_ipport_.Clear();
}
inline const ::std::string& getServerListReply::server_ipport(int index) const {
  // @@protoc_insertion_point(field_get:masterFrontend.getServerListReply.server_ipport)
  return server_ipport_.Get(index);
}
inline ::std::string* getServerListReply::mutable_server_ipport(int index) {
  // @@protoc_insertion_point(field_mutable:masterFrontend.getServerListReply.server_ipport)
  return server_ipport_.Mutable(index);
}
inline void getServerListReply::set_server_ipport(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:masterFrontend.getServerListReply.server_ipport)
  server_ipport_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void getServerListReply::set_server_ipport(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:masterFrontend.getServerListReply.server_ipport)
  server_ipport_.Mutable(index)->assign(std::move(value));
}
#endif
inline void getServerListReply::set_server_ipport(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  server_ipport_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:masterFrontend.getServerListReply.server_ipport)
}
inline void getServerListReply::set_server_ipport(int index, const char* value, size_t size) {
  server_ipport_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:masterFrontend.getServerListReply.server_ipport)
}
inline ::std::string* getServerListReply::add_server_ipport() {
  // @@protoc_insertion_point(field_add_mutable:masterFrontend.getServerListReply.server_ipport)
  return server_ipport_.Add();
}
inline void getServerListReply::add_server_ipport(const ::std::string& value) {
  server_ipport_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:masterFrontend.getServerListReply.server_ipport)
}
#if LANG_CXX11
inline void getServerListReply::add_server_ipport(::std::string&& value) {
  server_ipport_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:masterFrontend.getServerListReply.server_ipport)
}
#endif
inline void getServerListReply::add_server_ipport(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  server_ipport_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:masterFrontend.getServerListReply.server_ipport)
}
inline void getServerListReply::add_server_ipport(const char* value, size_t size) {
  server_ipport_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:masterFrontend.getServerListReply.server_ipport)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
getServerListReply::server_ipport() const {
  // @@protoc_insertion_point(field_list:masterFrontend.getServerListReply.server_ipport)
  return server_ipport_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
getServerListReply::mutable_server_ipport() {
  // @@protoc_insertion_point(field_mutable_list:masterFrontend.getServerListReply.server_ipport)
  return &server_ipport_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace masterFrontend

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_masterFrontend_2eproto
