// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterFrontend.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_masterFrontend_2eproto__INCLUDED
#define GRPC_masterFrontend_2eproto__INCLUDED

#include "masterFrontend.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace masterFrontend {

// 
class getKVipport final {
 public:
  static constexpr char const* service_full_name() {
    return "masterFrontend.getKVipport";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status receive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::masterFrontend::masterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterFrontend::masterReply>> Asyncreceive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterFrontend::masterReply>>(Asyncreceive_requestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterFrontend::masterReply>> PrepareAsyncreceive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterFrontend::masterReply>>(PrepareAsyncreceive_requestRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void receive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void receive_request(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::masterFrontend::masterReply* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterFrontend::masterReply>* Asyncreceive_requestRaw(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterFrontend::masterReply>* PrepareAsyncreceive_requestRaw(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status receive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::masterFrontend::masterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterFrontend::masterReply>> Asyncreceive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterFrontend::masterReply>>(Asyncreceive_requestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterFrontend::masterReply>> PrepareAsyncreceive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterFrontend::masterReply>>(PrepareAsyncreceive_requestRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void receive_request(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response, std::function<void(::grpc::Status)>) override;
      void receive_request(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::masterFrontend::masterReply* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::masterFrontend::masterReply>* Asyncreceive_requestRaw(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::masterFrontend::masterReply>* PrepareAsyncreceive_requestRaw(::grpc::ClientContext* context, const ::masterFrontend::frontendRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_receive_request_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status receive_request(::grpc::ServerContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_receive_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_receive_request() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_receive_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive_request(::grpc::ServerContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestreceive_request(::grpc::ServerContext* context, ::masterFrontend::frontendRequest* request, ::grpc::ServerAsyncResponseWriter< ::masterFrontend::masterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_receive_request<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_receive_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_receive_request() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::masterFrontend::frontendRequest, ::masterFrontend::masterReply>(
          [this](::grpc::ServerContext* context,
                 const ::masterFrontend::frontendRequest* request,
                 ::masterFrontend::masterReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->receive_request(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_receive_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive_request(::grpc::ServerContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void receive_request(::grpc::ServerContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_receive_request<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_receive_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_receive_request() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_receive_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive_request(::grpc::ServerContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_receive_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_receive_request() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_receive_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive_request(::grpc::ServerContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestreceive_request(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_receive_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_receive_request() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->receive_request(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_receive_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive_request(::grpc::ServerContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void receive_request(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_receive_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_receive_request() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::masterFrontend::frontendRequest, ::masterFrontend::masterReply>(std::bind(&WithStreamedUnaryMethod_receive_request<BaseClass>::Streamedreceive_request, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_receive_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status receive_request(::grpc::ServerContext* context, const ::masterFrontend::frontendRequest* request, ::masterFrontend::masterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedreceive_request(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::masterFrontend::frontendRequest,::masterFrontend::masterReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_receive_request<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_receive_request<Service > StreamedService;
};

}  // namespace masterFrontend


#endif  // GRPC_masterFrontend_2eproto__INCLUDED
