// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mail.proto

#include "mail.pb.h"
#include "mail.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mail {

static const char* Mail_method_names[] = {
  "/mail.Mail/GetMail",
};

std::unique_ptr< Mail::Stub> Mail::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Mail::Stub> stub(new Mail::Stub(channel));
  return stub;
}

Mail::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetMail_(Mail_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Mail::Stub::GetMail(::grpc::ClientContext* context, const ::mail::MailRequest& request, ::mail::MailReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetMail_, context, request, response);
}

void Mail::Stub::experimental_async::GetMail(::grpc::ClientContext* context, const ::mail::MailRequest* request, ::mail::MailReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetMail_, context, request, response, std::move(f));
}

void Mail::Stub::experimental_async::GetMail(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mail::MailReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetMail_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mail::MailReply>* Mail::Stub::AsyncGetMailRaw(::grpc::ClientContext* context, const ::mail::MailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mail::MailReply>::Create(channel_.get(), cq, rpcmethod_GetMail_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mail::MailReply>* Mail::Stub::PrepareAsyncGetMailRaw(::grpc::ClientContext* context, const ::mail::MailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mail::MailReply>::Create(channel_.get(), cq, rpcmethod_GetMail_, context, request, false);
}

Mail::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Mail_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Mail::Service, ::mail::MailRequest, ::mail::MailReply>(
          std::mem_fn(&Mail::Service::GetMail), this)));
}

Mail::Service::~Service() {
}

::grpc::Status Mail::Service::GetMail(::grpc::ServerContext* context, const ::mail::MailRequest* request, ::mail::MailReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mail

