// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: masterFrontend.proto

#include "masterFrontend.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace masterFrontend {
class frontendRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<frontendRequest> _instance;
} _frontendRequest_default_instance_;
class masterReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<masterReply> _instance;
} _masterReply_default_instance_;
}  // namespace masterFrontend
static void InitDefaultsfrontendRequest_masterFrontend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::masterFrontend::_frontendRequest_default_instance_;
    new (ptr) ::masterFrontend::frontendRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::masterFrontend::frontendRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_frontendRequest_masterFrontend_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsfrontendRequest_masterFrontend_2eproto}, {}};

static void InitDefaultsmasterReply_masterFrontend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::masterFrontend::_masterReply_default_instance_;
    new (ptr) ::masterFrontend::masterReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::masterFrontend::masterReply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_masterReply_masterFrontend_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmasterReply_masterFrontend_2eproto}, {}};

void InitDefaults_masterFrontend_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_frontendRequest_masterFrontend_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_masterReply_masterFrontend_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_masterFrontend_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_masterFrontend_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_masterFrontend_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_masterFrontend_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::masterFrontend::frontendRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::masterFrontend::frontendRequest, user_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::masterFrontend::masterReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::masterFrontend::masterReply, server_ipport_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::masterFrontend::frontendRequest)},
  { 6, -1, sizeof(::masterFrontend::masterReply)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::masterFrontend::_frontendRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::masterFrontend::_masterReply_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_masterFrontend_2eproto = {
  {}, AddDescriptors_masterFrontend_2eproto, "masterFrontend.proto", schemas,
  file_default_instances, TableStruct_masterFrontend_2eproto::offsets,
  file_level_metadata_masterFrontend_2eproto, 2, file_level_enum_descriptors_masterFrontend_2eproto, file_level_service_descriptors_masterFrontend_2eproto,
};

const char descriptor_table_protodef_masterFrontend_2eproto[] =
  "\n\024masterFrontend.proto\022\016masterFrontend\"$"
  "\n\017frontendRequest\022\021\n\tuser_name\030\001 \001(\t\"$\n\013"
  "masterReply\022\025\n\rserver_ipport\030\001 \001(\t2`\n\013ge"
  "tKVipport\022Q\n\017receive_request\022\037.masterFro"
  "ntend.frontendRequest\032\033.masterFrontend.m"
  "asterReply\"\000B4\n\026io.grpc.masterFrontendB\023"
  "masterFrontendProtoP\001\242\002\002MFb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_masterFrontend_2eproto = {
  false, InitDefaults_masterFrontend_2eproto, 
  descriptor_table_protodef_masterFrontend_2eproto,
  "masterFrontend.proto", &assign_descriptors_table_masterFrontend_2eproto, 274,
};

void AddDescriptors_masterFrontend_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_masterFrontend_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_masterFrontend_2eproto = []() { AddDescriptors_masterFrontend_2eproto(); return true; }();
namespace masterFrontend {

// ===================================================================

void frontendRequest::InitAsDefaultInstance() {
}
class frontendRequest::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int frontendRequest::kUserNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

frontendRequest::frontendRequest()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:masterFrontend.frontendRequest)
}
frontendRequest::frontendRequest(const frontendRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  user_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.user_name().size() > 0) {
    user_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_name_);
  }
  // @@protoc_insertion_point(copy_constructor:masterFrontend.frontendRequest)
}

void frontendRequest::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_frontendRequest_masterFrontend_2eproto.base);
  user_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

frontendRequest::~frontendRequest() {
  // @@protoc_insertion_point(destructor:masterFrontend.frontendRequest)
  SharedDtor();
}

void frontendRequest::SharedDtor() {
  user_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void frontendRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const frontendRequest& frontendRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_frontendRequest_masterFrontend_2eproto.base);
  return *internal_default_instance();
}


void frontendRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:masterFrontend.frontendRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* frontendRequest::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<frontendRequest*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string user_name = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("masterFrontend.frontendRequest.user_name");
        object = msg->mutable_user_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool frontendRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:masterFrontend.frontendRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string user_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_user_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->user_name().data(), static_cast<int>(this->user_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "masterFrontend.frontendRequest.user_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:masterFrontend.frontendRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:masterFrontend.frontendRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void frontendRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:masterFrontend.frontendRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string user_name = 1;
  if (this->user_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->user_name().data(), static_cast<int>(this->user_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterFrontend.frontendRequest.user_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->user_name(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:masterFrontend.frontendRequest)
}

::google::protobuf::uint8* frontendRequest::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:masterFrontend.frontendRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string user_name = 1;
  if (this->user_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->user_name().data(), static_cast<int>(this->user_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterFrontend.frontendRequest.user_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->user_name(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterFrontend.frontendRequest)
  return target;
}

size_t frontendRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterFrontend.frontendRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string user_name = 1;
  if (this->user_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->user_name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void frontendRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:masterFrontend.frontendRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const frontendRequest* source =
      ::google::protobuf::DynamicCastToGenerated<frontendRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:masterFrontend.frontendRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:masterFrontend.frontendRequest)
    MergeFrom(*source);
  }
}

void frontendRequest::MergeFrom(const frontendRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:masterFrontend.frontendRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.user_name().size() > 0) {

    user_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_name_);
  }
}

void frontendRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:masterFrontend.frontendRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void frontendRequest::CopyFrom(const frontendRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterFrontend.frontendRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool frontendRequest::IsInitialized() const {
  return true;
}

void frontendRequest::Swap(frontendRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void frontendRequest::InternalSwap(frontendRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  user_name_.Swap(&other->user_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata frontendRequest::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_masterFrontend_2eproto);
  return ::file_level_metadata_masterFrontend_2eproto[kIndexInFileMessages];
}


// ===================================================================

void masterReply::InitAsDefaultInstance() {
}
class masterReply::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int masterReply::kServerIpportFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

masterReply::masterReply()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:masterFrontend.masterReply)
}
masterReply::masterReply(const masterReply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  server_ipport_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.server_ipport().size() > 0) {
    server_ipport_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.server_ipport_);
  }
  // @@protoc_insertion_point(copy_constructor:masterFrontend.masterReply)
}

void masterReply::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_masterReply_masterFrontend_2eproto.base);
  server_ipport_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

masterReply::~masterReply() {
  // @@protoc_insertion_point(destructor:masterFrontend.masterReply)
  SharedDtor();
}

void masterReply::SharedDtor() {
  server_ipport_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void masterReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const masterReply& masterReply::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_masterReply_masterFrontend_2eproto.base);
  return *internal_default_instance();
}


void masterReply::Clear() {
// @@protoc_insertion_point(message_clear_start:masterFrontend.masterReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  server_ipport_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* masterReply::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<masterReply*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string server_ipport = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("masterFrontend.masterReply.server_ipport");
        object = msg->mutable_server_ipport();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool masterReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:masterFrontend.masterReply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string server_ipport = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_server_ipport()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->server_ipport().data(), static_cast<int>(this->server_ipport().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "masterFrontend.masterReply.server_ipport"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:masterFrontend.masterReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:masterFrontend.masterReply)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void masterReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:masterFrontend.masterReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string server_ipport = 1;
  if (this->server_ipport().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->server_ipport().data(), static_cast<int>(this->server_ipport().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterFrontend.masterReply.server_ipport");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->server_ipport(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:masterFrontend.masterReply)
}

::google::protobuf::uint8* masterReply::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:masterFrontend.masterReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string server_ipport = 1;
  if (this->server_ipport().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->server_ipport().data(), static_cast<int>(this->server_ipport().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterFrontend.masterReply.server_ipport");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->server_ipport(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterFrontend.masterReply)
  return target;
}

size_t masterReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterFrontend.masterReply)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string server_ipport = 1;
  if (this->server_ipport().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->server_ipport());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void masterReply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:masterFrontend.masterReply)
  GOOGLE_DCHECK_NE(&from, this);
  const masterReply* source =
      ::google::protobuf::DynamicCastToGenerated<masterReply>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:masterFrontend.masterReply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:masterFrontend.masterReply)
    MergeFrom(*source);
  }
}

void masterReply::MergeFrom(const masterReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:masterFrontend.masterReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.server_ipport().size() > 0) {

    server_ipport_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.server_ipport_);
  }
}

void masterReply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:masterFrontend.masterReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void masterReply::CopyFrom(const masterReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterFrontend.masterReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool masterReply::IsInitialized() const {
  return true;
}

void masterReply::Swap(masterReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void masterReply::InternalSwap(masterReply* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  server_ipport_.Swap(&other->server_ipport_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata masterReply::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_masterFrontend_2eproto);
  return ::file_level_metadata_masterFrontend_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace masterFrontend
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::masterFrontend::frontendRequest* Arena::CreateMaybeMessage< ::masterFrontend::frontendRequest >(Arena* arena) {
  return Arena::CreateInternal< ::masterFrontend::frontendRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::masterFrontend::masterReply* Arena::CreateMaybeMessage< ::masterFrontend::masterReply >(Arena* arena) {
  return Arena::CreateInternal< ::masterFrontend::masterReply >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
